apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
  - name: IMAGE
    description: The URI of the image to push, including registry host
    default: ""
  - name: DIRECTORY
    description: The subdirectory of the workspace/repo
    default: ""
  - name: DOCKERFILE
    description: File name to build docker image
    default: Dockerfile
  - name: TAG
    default: latest
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.6.0
    args:
    - --context=/workspace/${DIRECTORY}
    - --dockerfile=/workspace/${DIRECTORY}/${DOCKERFILE}
    - --destination=${IMAGE}:${TAG}
