apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
  - name: IMAGE
    description: The URI of the image to push, including registry host
    default: null
  - name: TAG
    description: Tag of the image being pushed
    default: latest
  - name: DIRECTORY
    description: The subdirectory of the workspace/repo
    default: ""

  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --context=/workspace/${DIRECTORY}
    - --dockerfile=/workspace/${DIRECTORY}/Dockerfile
    - --destination=${IMAGE}:${TAG}

